addons:
    apt:
        packages:
            - pandoc
language: python
cache: pip
python:
  - "3.6"
  - "3.7"
  - "3.8"
  - "3.9"
# command to install dependencies
install:
  - pip install --upgrade -r requirements.txt
  - pip install --upgrade tox-travis
  - pip install --upgrade .
# command to run tests
script: tox
after_success: coveralls
